
title: My journey thoughout digital humanities
description: I'm Nick and I have researched and worked hard to establish a website that corresponds with my discoveries with digital humanities. View below some of this work. 
remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

